### ISSUE TITLE
Self Signed certificate support

### ISSUE THREAD

**Issue by aramacciotti** [swellaby/vsts-mirror-git-repository#6] opened 2018-05-06 10:24 UTC
Is it possible to add something like "-c http.sslVerify=false " to the clone command in order to make self signed certificate accepted if the case?

**Comment by calebcartwright** [comment] 2018-05-06 14:36
Yeah I think we can add that. 

@traviskosarek - my initial thinking is that a task input should control whether or not to include the flag. thoughts?

**Comment by traviskosarek** [comment] 2018-05-06 15:32
I can definitely take this on. Using the git command flag @aramacciotti mentioned looks like the most secure and direct way to accomplish this for git servers with self-signed certificates.

@calebcartwright Yep, I think from the task point of view, a simple checkbox would be the best fit. I think adding a checkbox named "Verify SSL" that defaults to being checked is the most clear.

In this case, to disable the SSL verification, the user would simply uncheck the "Verify SSL" checkbox. Thoughts or suggestions?

**Comment by calebcartwright** [comment] 2018-05-06 15:46
SGTM

**Comment by aramacciotti** [comment] 2018-05-06 17:33
My opition: It would be great!

**Comment by traviskosarek** [comment] 2018-05-06 23:05
@aramacciotti I have updated the extension to include your suggestion. Let me know if you have any issues!

I am also going to close this issue as the enhancement has been released in version 1.1.0

**Comment by aramacciotti** [comment] 2018-05-07 10:44
I'm getting the following log. Any suggestion?

```
******************************************************************************
Starting: Mirror Git Repository to https://...........
******************************************************************************
==============================================================================
Task         : Mirror Git Repository
Description  : A straightforward utility to mirror one Git repository to another location
Version      : 1.1.2
Author       : Swellaby
Help         : [More Information](https://github.com/swellaby/vsts-mirror-git-repository)
==============================================================================
C:\agents\2.133.3\externals\git\cmd\git.exe -c http.sslVerify=true clone --mirror https://..........................
Cloning into bare repository 'SICOGE.git'...
C:\agents\2.133.3\externals\git\cmd\git.exe -c http.sslVerify=false -C SICOGE.git push --mirror https://....PAT.....@....target repository url ....
******************************************************************************
Starting: Post Job Cleanup
******************************************************************************
Cleaning any cached credential from repository: SICOGE (Git)
git remote set-url origin https://......
git remote set-url --push origin https://........
******************************************************************************
Finishing: Post Job Cleanup
******************************************************************************
******************************************************************************
Finishing: Job
******************************************************************************
/usr/bin/bash: /dev/tty: **No such device or address**
error: failed to execute prompt script (exit code 1)
fatal: **could not read Password for** 'https://....PAT....@...server name....': **No error**
Error: C:\agents\2.133.3\externals\git\cmd\**git.exe failed with return code: 12**8
```

**Comment by aramacciotti** [comment] 2018-05-07 10:57
Is your code using your own Git version? I read that there's a bug in version 1.8.5 that raise that error (I mean _could not read Password for_...) resolved in 1.9.0. Could be that the case?

**Comment by aramacciotti** [comment] 2018-05-07 15:52
At Job log I see also these other lines. Does it mean that Git version is 1.8.3 or 2.14.3?

`2018-05-07T10:35:44.3516864Z ##[command]git version
2018-05-07T10:35:44.4133521Z git version 2.14.3.windows.1
2018-05-07T10:35:44.4241196Z ##[command]git lfs version
2018-05-07T10:35:47.4889125Z git-lfs/2.4.0 (GitHub; windows amd64; go 1.8.3; git 1a98fa5c)`

**Comment by traviskosarek** [comment] 2018-05-07 15:58
The task is only executing the Git commands, so it will use whatever version of Git it finds locally. So we should be able to rule out the task dictating a specific version or bundling it's own version of Git.

I am using the vsts-agent docker image ( https://hub.docker.com/r/microsoft/vsts-agent/ ). My current running image is using Git version 2.16.1

As far as the error you are seeing, I came across this thread (https://github.com/atom/atom/issues/8984) with others that have experienced similar issues. The cause of some of their issues were needing to tell Git that they were using cygwin as their bash command executor.

Is your environment using a TFS server with Cygwin installed?

**Comment by traviskosarek** [comment] 2018-05-07 15:59
In your log, that would mean it is using Git version 2.14.3

**Comment by aramacciotti** [comment] 2018-05-07 16:06
My environment is VSTS (VisualStudio Online), I mean "Hosted VS2017" agent of a VSTS instance

**Comment by traviskosarek** [comment] 2018-05-07 16:57
I tried reproducing this in a Hosted VS2017 and it seems to be working for me within that environment. That said, the only difference I believe is that I do not have a Git server with a self-signed certificate to fully verify it.

My guess at the moment is that the issue is that the build agent is not receiving any feedback when doing the git push. Have you tried running the commands manually? This is not ideal as that is what the task is supposed to be for, but it may help get to the root cause of the issue.

Would you mind trying to run these commands manually?
git -c http.sslVerify=false clone --mirror https://**{source repo pat}**@**{source repo address}**
git -c http.sslVerify=false -C **{source repo name}**.git push --mirror https://**{destination repo pat}**@**{destination repo address}**

I am wondering if the task is hanging, waiting for feedback or if there is another error occurring that is not being sent to the build agent's console output

**Comment by aramacciotti** [comment] 2018-05-07 20:08
I'm trying but it will take a while... 
The task doesn't wait for any feedback and no other error is sent to the agent console.
Thanks for the support, I'll provide feedback about executing commands manually from my local development environment

**Comment by aramacciotti** [comment] 2018-05-07 21:28
Executing manually by using Git for Windows it works fine. Unfortunately I gave again a try by using the agent getting the same error as before

**Comment by calebcartwright** [comment] 2018-05-07 21:51
@aramacciotti - when you executed the command manually on the hosted build agent from your build definition, which build task did you use in your build definition (powershell script, command line, batch script, or something different)?

**Comment by aramacciotti** [comment] 2018-05-08 06:41
Let me clarify as I made some addition test:

1. when I said "manually", I meant that I executed the commands directly in my development environment not using any build agent
2. I tried then to add a "Run script" task to my CI pipeline and execute exacly the same commands and I got exacly the same error that I got with your task

Task         : Batch Script
Description  : Run a windows cmd or bat script and optionally allow it to change the environment
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613733)
==============================================================================
D:\a\1\s\mirror.cmd 

D:\a\1\s>git -c http.sslVerify=false clone --mirror https://......./_git/SICOGE 
Cloning into bare repository 'SICOGE.git'...

D:\a\1\s>git -c http.sslVerify=false -C SICOGE.git push --mirror https://......../SICOGE.git 
/usr/bin/bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Password for 'https://........': No error
Process completed with exit code 128.

**Comment by aramacciotti** [comment] 2018-05-08 08:43
I got a solution by executing the commands in a Batch Script and using username and password instead of PAT. That's really strange by me and I understand you cannot solve that issue otherwise than the same way but ask to provide username and password couldn't be an acceptable solution.
Probably the correct way is to raise the issue with Microsoft

**Comment by traviskosarek** [comment] 2018-05-08 16:26
Hmm, that is really strange. I am not sure why username/password works and a PAT does not. Thank you for doing the leg work!

I am going to open a new potential enhancement option for using username/password instead of PAT because I think that might be another viable option for the future.

That said, the task is not doing any type of validation on the PAT, so if you did want to continue to use the task, you _could_ just put your "username:password" in the PAT field instead of a PAT token. I realize this is not necessarily ideal because of the label within the task, but this should provide a workaround in the mean time.

Either way, thank you for your help in digging into this issue!

**Comment by traviskosarek** [comment] 2018-05-08 16:44
I am going to close this issue because I believe the enhancement is successful, but I did open issue #10 for further enhancements to add username/password functionality.

**Closed by traviskosarek** 2018-05-08 16:44 UTC
Labels: enhancement

**Comment by calebcartwright** [comment] 2018-05-08 16:54
@aramacciotti thanks for the additional details. Would you mind sharing what the git hosting is solution for both your source and destination repos (I assume one of them is VSTS or TFS). 

Also, if there's any info you'd rather share in an offline channel you can email us at opensource@swellaby.com

**Comment by aramacciotti** [comment] 2018-05-08 19:02
Source is on VSTS and target is on GitLab (private).
I had to disable SSL verification only on target.
