### ISSUE TITLE
How do I mirror a Azure Repo to Bitbucket Server?

### ISSUE THREAD

**Issue by SunainaDG** [swellaby/vsts-mirror-git-repository#58] opened 2020-01-04 13:30 UTC
**Question**

I have a DevOps account, I am using Azure Repos as my version control system. I want to update my Bitbucket server repo through a CI pipeline using this task.

Source: Azure Repos
Destination: Bitbucket Server personal repository

I have a PAT for the Azure Repos with read access, and till this part everything is working fine (it can mirror clone the data inside the agent)
I have a PAT for my bitbucket server account also, with admin access to my personal repository.
When the agent tries to push to the Server account it says:

"fatal: unable to access https://<username>:<accesstoken>@rd-bitbucket.app.pmi/scm/~sdasgupt1/cigstockspoc.git/': Could not resolve host: rd-bitbucket.app.pmi"

however when I try to do the same thing from my cmd prompt everthing just works fine.
Where am I going wrong?

**Comment by calebcartwright** [comment] 2020-01-04 22:49
Hey there @SunainaDG! 

Few questions for you:
1) is your Bitbucket Server instance internet accessible, or hosted on a private network?
2) is your Azure Pipeline that includes the Mirror task step running on a self-hosted Azure Pipelines agent or one of the Microsoft-hosted agent pools?

**Comment by SunainaDG** [comment] 2020-01-05 04:42
1. I’m not sure if it’s private or not. But I access it only from within my workspace network. Whenever I try to access it outside that network it says server not found. And I think internet access is their. Because obviously it’s hosted in Neufchâtel and I access it from India.
2. No it was Microsoft hosted.

But for your information (if this can b of any help)- it worked when I tried hosting the agent in my computer. Because I figured the Microsoft hosted agent was not being able to access the server probably because of the network.

**Comment by calebcartwright** [comment] 2020-01-05 15:19
> Whenever I try to access it outside that network it says server not found.

That's going to be the problem then. The issue is with network connectivity from the pipeline agent to your target/destination, not with this git mirror task. 

You're going to have to run a self-hosted pipeline agent that has network connectivity to your BB Server instance, and ensure your piepline runs on that self-hosted agent (not the Microsoft hosted agent)

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#install

**Comment by SunainaDG** [comment] 2020-01-06 04:14
Ahh. I figured that out. But I thought I was taking the easy route and I was doing something wrong with the task.

Anyways, one last query- what is the extent of the mirror that this task performs? Like what all does it duplicate?

**Comment by calebcartwright** [comment] 2020-01-06 04:23
No worries! 

> Anyways, one last query- what is the extent of the mirror that this task performs? Like what all does it duplicate?

It's leveraging git's `--mirror` flags which basically means everything (all refs). The one exception is that this task deliberately excludes the underlying refs associated with PRs that some git providers (like GitHub) maintain, since those can't be pushed. 

More detailed info on `--mirror` can be found in the docs:
https://git-scm.com/docs/git-clone#git-clone---mirror

And this walkthrough from GitHub is the basic set of high level steps this task follows:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository

**Comment by calebcartwright** [comment] 2020-01-07 03:38
I'm going to go ahead and close this @SunainaDG, hope this helped!

**Closed by calebcartwright** 2020-01-07 03:38 UTC
Labels: question
