### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Jamesits** [swellaby/vsts-mirror-git-repository#31] opened 2018-12-13 05:45 UTC
## Environment Details

* **Pipeline**
    
  * [x] Build
  * [ ] Release
* **Agent Type**
    
  * [x] Hosted Agent
  * [ ] Self-hosted/private Agent
* **Agent OS**
    
  * [x] Linux
  * [x] Mac
  * [ ] Windows
* **Agent Tool Versions**
  * **Mirror Git Repo Task version**: 1.1.7
  

## Description

This happens when "Source Repository - Personal Access Token" is empty.

There are 2 problems:

1. There is some weird error message
2. The task ended up as "succeeded" and it fails actually

## Log Output
```
2018-12-13T05:40:39.0037948Z ##[section]Starting: Mirror Git Repository to somewhere
2018-12-13T05:40:39.0369605Z ==============================================================================
2018-12-13T05:40:39.0369763Z Task         : Mirror Git Repository
2018-12-13T05:40:39.0369824Z Description  : A straightforward utility to mirror one Git repository to another location
2018-12-13T05:40:39.0369880Z Version      : 1.1.7
2018-12-13T05:40:39.0369944Z Author       : Swellaby
2018-12-13T05:40:39.0370378Z Help         : [More Information](https://github.com/swellaby/vsts-mirror-git-repository)
2018-12-13T05:40:39.0370492Z ==============================================================================
2018-12-13T05:40:41.1745689Z [command]/usr/bin/git -c http.sslVerify=true clone --mirror https://null@github.com/Jamesits/some-private-repo
2018-12-13T05:40:41.1746156Z Cloning into bare repository 'some-private-repo'...
2018-12-13T05:40:42.8078651Z fatal: could not read Password for 'https://null@github.com': No such device or address
2018-12-13T05:40:42.9111186Z path.js:78
2018-12-13T05:40:42.9112093Z function normalizeStringPosix(path, allowAboveRoot) {
2018-12-13T05:40:42.9112277Z                              ^
2018-12-13T05:40:42.9112598Z 
2018-12-13T05:40:42.9113057Z RangeError: Maximum call stack size exceeded
2018-12-13T05:40:42.9113121Z     at normalizeStringPosix (path.js:78:30)
2018-12-13T05:40:42.9113229Z     at Object.normalize (path.js:1186:12)
2018-12-13T05:40:42.9113281Z     at Object.join (path.js:1221:18)
2018-12-13T05:40:42.9114667Z     at _ (/home/vsts/work/_tasks/mirror-git-repository-vsts-task_4e842f83-9438-4acb-994c-c8c31137dea9/1.1.7/git-mirror-task.js:1:15082)
2018-12-13T05:40:42.9115166Z     at S (/home/vsts/work/_tasks/mirror-git-repository-vsts-task_4e842f83-9438-4acb-994c-c8c31137dea9/1.1.7/git-mirror-task.js:1:14947)
2018-12-13T05:40:42.9115534Z     at _ (/home/vsts/work/_tasks/mirror-git-repository-vsts-task_4e842f83-9438-4acb-994c-c8c31137dea9/1.1.7/git-mirror-task.js:1:15078)
2018-12-13T05:40:42.9115971Z     at S (/home/vsts/work/_tasks/mirror-git-repository-vsts-task_4e842f83-9438-4acb-994c-c8c31137dea9/1.1.7/git-mirror-task.js:1:14947)
2018-12-13T05:40:42.9116321Z     at _ (/home/vsts/work/_tasks/mirror-git-repository-vsts-task_4e842f83-9438-4acb-994c-c8c31137dea9/1.1.7/git-mirror-task.js:1:15078)
2018-12-13T05:40:42.9116713Z     at S (/home/vsts/work/_tasks/mirror-git-repository-vsts-task_4e842f83-9438-4acb-994c-c8c31137dea9/1.1.7/git-mirror-task.js:1:14947)
2018-12-13T05:40:42.9117083Z     at _ (/home/vsts/work/_tasks/mirror-git-repository-vsts-task_4e842f83-9438-4acb-994c-c8c31137dea9/1.1.7/git-mirror-task.js:1:15078)
2018-12-13T05:40:42.9299089Z ##[section]Finishing: Mirror Git Repository to somewhere
```

**Comment by calebcartwright** [comment] 2018-12-13 06:04
Hi @Jamesits - it looks like your source repository is a GitHub repo at: https://github.com/Jamesits/some-private-repo. I don't see that anywhere as a public repo on your GH profile, and the repo name would indicate that it is a private repository, however, the output also indicates that you are not providing a PAT in the task configuration. Is that correct?

**Comment by Jamesits** [comment] 2018-12-13 06:09
@calebcartwright Yes. I had some more tests: any error on repo URL or auth (didn't try other errors) would result in a `RangeError: Maximum call stack size exceeded` and the task would report a "succeeded" to the pipeline.

**Comment by calebcartwright** [comment] 2018-12-13 06:34
Thanks for letting us know. The task should result in a failed result in that condition so I've marked this as a bug. 

However, for the use case described initially in this issue, you'll need to provide a PAT in order to access private repo, in any system.

I don't have a clue where the underlying call stack error is coming from 😄 but we'll look into it!

**Comment by calebcartwright** [comment] 2018-12-14 00:41
Well this is fascinating.. when I run the script locally, directly against the .js file emitted by the transpiler, the task executes as expected, and fails on the clone fail step. However, when doing the exact same thing but running the bundled file created by webpack, I can reproduce the reported error (max call stack size exceeded).

Is this a bundling issue?

**Comment by Rocinante89** [comment] 2019-01-10 21:02
Just checking in to say that I'm experiencing the same issue.

**Comment by calebcartwright** [comment] 2019-01-10 23:41
Thanks @Rocinante89 

Are you seeing this under the same circumstances (using a private repository without specifying the required PAT for that repository), or different circumstances?

**Comment by Rocinante89** [comment] 2019-01-11 10:30
@calebcartwright I'm using a private repo but I have specified the required PAT for it

**Comment by Jamesits** [comment] 2019-01-11 11:40
@Rocinante89 Try use `username:PAT` for PAT and `https://example.com/some-repo.git` (i.e. no username) for git URL.

**Comment by calebcartwright** [comment] 2019-01-11 16:00
@Rocinante89 thanks. What's the provider for your source & destination? We've updated our Bug template to request some of these other data points but no need to create another issue, just including it for reference (https://github.com/swellaby/vsts-mirror-git-repository/blob/master/.github/ISSUE_TEMPLATE/01_BUG_TEMPLATE.md)

In addition to fixing the underlying bug in the bundling (#34) I think we probably also need to update our documentation around authentication with the different providers

**Comment by Rocinante89** [comment] 2019-01-11 16:48
The source provider is an Azure DevOps private repo & the source is a private GitHub repo.

**Comment by Rocinante89** [comment] 2019-01-12 12:43
I ran the build and can confirm that I'm no longer getting the call stack error 👍

**Comment by Jamesits** [comment] 2019-01-12 15:21
hmm I currently do not have any good way to test it out... I'll just assume it works.

**Comment by calebcartwright** [comment] 2019-01-12 19:02
Perfect thanks! Going to close this now, and as always feel free to reach out to us with any questions

**Closed by calebcartwright** 2019-01-12 19:02 UTC
Labels: bug, help wanted
